const ENDPOINTS_CODE = {
  CATEGORY_ALL: "CATEGORY_ALL",
  PRODUCTS_ALL: "PRODUCTS_ALL",
  PRODUCT_DETAIL: "PRODUCT_DETAIL",
}

const ENV = {
  PRODUCTION: "PRODUCTION",
  DEVELOPMENT: "DEVELOPMENT",
  LOCAL: "LOCAL",
}

export { ENDPOINTS_CODE, ENV }
