const ENDPOINTS_CODE = {
  CATEGORY_ALL: "CATEGORY_ALL",
  PRODUCTS_ALL: "PRODUCTS_ALL",
  PRODUCT_DETAIL: "PRODUCT_DETAIL",
  USERS_ALL: "USERS_ALL",
  EXIST_NAME: "EXIST_NAME",
  USER_CREATE: "USER_CREATE",
  PRODUCT_CREATE: "PRODUCT_CREATE",
  PRODUCT_EDIT: "PRODUCT_EDIT",
  USER_EDIT_ROLE: "USER_EDIT_ROLE",
  USER_VALIDATION: "USER_VALIDATION",
}

const ENV = {
  PRODUCTION: "PRODUCTION",
  DEVELOPMENT: "DEVELOPMENT",
  LOCAL: "LOCAL",
}

export { ENDPOINTS_CODE, ENV }
