const ENDPOINTS_CODE = {
  CATEGORY_ALL: "CATEGORY_ALL",
  PRODUCTS_ALL: "PRODUCTS_ALL",
  PRODUCT_DETAIL: "PRODUCT_DETAIL",
  USERS_ALL: "USERS_ALL",
  EXIST_NAME: "EXIST_NAME",
}

const ENV = {
  PRODUCTION: "PRODUCTION",
  DEVELOPMENT: "DEVELOPMENT",
  LOCAL: "LOCAL",
}

export { ENDPOINTS_CODE, ENV }
